# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoodip4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neighborhood',
            old_name='neighborhood_name',
            new_name='name',
        ),
    ]
