# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hoodip4', '0002_auto_20181022_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='business_images/'),
            preserve_default=False,
        ),
    ]
